version: '3'
services:
  postgrest:
    image: postgrest/postgrest
    environment:
      PGRST_DB_URI: postgres://r7admin:r7password@db:5432/r7platform
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_JWT_SECRET: jwt_secret_key
      PGRST_DB_MAX_ROWS: 500
      PGRST_DB_POOL: 50
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5444:5432"
    environment:
      POSTGRES_DB: r7platform
      POSTGRES_USER: r7admin
      POSTGRES_PASSWORD: r7password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"

  nginx:
    image: nginx:stable-alpine
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always